### ISSUE TITLE
Fisherman profession not showing icon

### ISSUE THREAD

**Issue by disgusdad** [FWolfe/ProfessionsFramework#3]
\examples\default_professions.lua

Fisherman icon not defined, cost is declared twice. Line 136

**Comment by FWolfe** [comment]
Thanks, my bad I didn't actually load up and test the examples. Eventually they'll make their way into the core as a option for using the PF versions instead of the vanilla definitions since some things can't be edited in the vanilla ones. Just didn't the time to properly throw them in yet.
